name: Build Raspberry Pi Packages

on:
  push:
  #    branches: [main]
  #  pull_request:

  workflow_dispatch:

jobs:
  RaspiOS:
    runs-on: ubuntu-24.04-arm

    strategy:
      matrix:
        target_arch: [arm64]  # No binutils-i686-linux-gnu:armhf :-(
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Set up for chroot
        run: |
          sudo apt update
          sudo apt install -y debootstrap
          sudo debootstrap --arch ${{ matrix.target_arch }} --foreign bookworm `pwd`/raspios http://ftp2.de.debian.org/debian
          sudo cp /etc/resolv.conf raspios/etc/.
          sudo chroot raspios /bin/bash -c "/debootstrap/debootstrap --second-stage"
          #for i in dev proc sys ; do
          #  [ -d raspios/$i ] || sudo mkdir raspios/$i
          #  sudo mount --bind /$1 raspios/$i
          #done

      - name: Set up in chroot environment
        run: |
          sudo chroot raspios /bin/bash -c ./build.sh

      - name: Thunk-gen
        run: |
          sudo chroot raspios /bin/bash -c ./build-thunk-gen.sh

      - name: SmallerC
        run: |
          sudo chroot raspios /bin/bash -c ./build-smallerc.sh

      - name: Djstub
        run: |
          sudo chroot raspios /bin/bash -c ./build-djstub.sh

      - name: Dj64dev
        run: |
          sudo chroot raspios /bin/bash -c ./build-dj64dev.sh

      - name: Nasm-segelf
        run: |
          sudo chroot raspios /bin/bash -c ./build-nasm-segelf.sh

      - name: Fdpp
        run: |
          sudo chroot raspios /bin/bash -c ./build-fdpp.sh

      - name: Comcom64
        run: |
          sudo chroot raspios /bin/bash -c ./build-comcom64.sh

      - name: Dosemu2
        run: |
          sudo chroot raspios /bin/bash -c ./build-dosemu2.sh

      - name: Install FreeDOS Userspace
        run: |
          sudo chroot raspios /bin/bash -c ./build-insfdusr.sh

      - name: Upload built packages
        uses: actions/upload-artifact@v4
        with:
          name: raspios-${{ matrix.target_arch }}
          path: raspios/*.deb
